-- =====================================================================
-- PennyPal - seed and test data
-- Generated by tool/export_seed_sql_test.dart on 2026-09-24.
-- Run after pennypal_schema.sql:  sqlite3 pennypal.db < pennypal_seed_data.sql
-- Demo transactions are dated relative to the generation date.
-- Logins: admin@pennypal.app / Admin@123, student@pennypal.app / Student@123
-- =====================================================================

BEGIN TRANSACTION;

-- Users (2)
INSERT INTO Users (UserId, FullName, Email, MobileNumber, PasswordHash, Role, IsActive, CreatedAt, LastLogin) VALUES ('user-admin-0001', 'PennyPal Administrator', 'admin@pennypal.app', '+10000000000', 'pbkdf2$10000$B0YUlb6BsDPcwg0Sy8eOmQ==$N8eZPOtGYhOpKRk0y+HufMxksCTNz1yn/Z4KIX1LweY=', 'admin', 1, '2026-09-24T14:43:53.874524', NULL);
INSERT INTO Users (UserId, FullName, Email, MobileNumber, PasswordHash, Role, IsActive, CreatedAt, LastLogin) VALUES ('user-student-0001', 'Ada Student', 'student@pennypal.app', '+15550100200', 'pbkdf2$10000$+Q9Ob7PQhIyEh7GiFk3e9w==$eAB8gUXGKBP3tJcf58MQOwcYS3lHYG1n6K8+J9M/WiQ=', 'student', 1, '2026-09-24T14:43:53.874524', NULL);

-- UserProfiles (2)
INSERT INTO UserProfiles (ProfileId, UserId, StudentStatus, CurrencyPreference, NotificationPreference, ProfileImage) VALUES ('profile-admin-0001', 'user-admin-0001', NULL, 'USD', 1, NULL);
INSERT INTO UserProfiles (ProfileId, UserId, StudentStatus, CurrencyPreference, NotificationPreference, ProfileImage) VALUES ('profile-student-0001', 'user-student-0001', 'Undergraduate', 'USD', 1, NULL);

-- Categories (8)
INSERT INTO Categories (CategoryId, CategoryName, CategoryType, Icon, IsDefault, CreatedBy) VALUES ('cat-food', 'Food', 'expense', 'food', 1, NULL);
INSERT INTO Categories (CategoryId, CategoryName, CategoryType, Icon, IsDefault, CreatedBy) VALUES ('cat-transport', 'Transport', 'expense', 'transport', 1, NULL);
INSERT INTO Categories (CategoryId, CategoryName, CategoryType, Icon, IsDefault, CreatedBy) VALUES ('cat-education', 'Education', 'expense', 'education', 1, NULL);
INSERT INTO Categories (CategoryId, CategoryName, CategoryType, Icon, IsDefault, CreatedBy) VALUES ('cat-shopping', 'Shopping', 'expense', 'shopping', 1, NULL);
INSERT INTO Categories (CategoryId, CategoryName, CategoryType, Icon, IsDefault, CreatedBy) VALUES ('cat-entertainment', 'Entertainment', 'expense', 'entertainment', 1, NULL);
INSERT INTO Categories (CategoryId, CategoryName, CategoryType, Icon, IsDefault, CreatedBy) VALUES ('cat-bills', 'Bills', 'expense', 'bills', 1, NULL);
INSERT INTO Categories (CategoryId, CategoryName, CategoryType, Icon, IsDefault, CreatedBy) VALUES ('cat-savings', 'Savings', 'expense', 'savings', 1, NULL);
INSERT INTO Categories (CategoryId, CategoryName, CategoryType, Icon, IsDefault, CreatedBy) VALUES ('cat-misc', 'Miscellaneous', 'expense', 'misc', 1, NULL);

-- Transactions (38)
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-001', 'user-student-0001', 'income', 500.0, NULL, 'Monthly allowance', NULL, '2026-07-01', 'Bank transfer', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-002', 'user-student-0001', 'income', 180.0, NULL, 'Part-time tutoring', NULL, '2026-07-15', 'Bank transfer', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-003', 'user-student-0001', 'expense', 42.5, 'cat-food', NULL, 'Groceries at supermarket', '2026-07-02', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-004', 'user-student-0001', 'expense', 25.0, 'cat-transport', NULL, 'Monthly bus pass', '2026-07-03', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-005', 'user-student-0001', 'expense', 12.99, 'cat-entertainment', NULL, 'Netflix subscription', '2026-07-05', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-006', 'user-student-0001', 'expense', 18.4, 'cat-food', NULL, 'Pizza with friends', '2026-07-07', 'Cash', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-007', 'user-student-0001', 'expense', 35.0, 'cat-bills', NULL, 'Phone data plan', '2026-07-09', 'Mobile money', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-008', 'user-student-0001', 'expense', 90.0, 'cat-education', NULL, 'Textbooks and printing', '2026-07-11', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-009', 'user-student-0001', 'expense', 22.75, 'cat-food', NULL, 'Cafeteria lunches', '2026-07-13', 'Cash', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-010', 'user-student-0001', 'expense', 35.0, 'cat-shopping', NULL, 'New t-shirt', '2026-07-16', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-011', 'user-student-0001', 'expense', 50.0, 'cat-savings', NULL, 'Transfer to savings', '2026-07-20', 'Cash', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-012', 'user-student-0001', 'expense', 9.5, 'cat-transport', NULL, 'Uber ride home', '2026-07-22', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-013', 'user-student-0001', 'expense', 15.0, 'cat-entertainment', NULL, 'Cinema tickets', '2026-07-25', 'Cash', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-014', 'user-student-0001', 'income', 500.0, NULL, 'Monthly allowance', NULL, '2026-08-01', 'Bank transfer', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-015', 'user-student-0001', 'expense', 42.5, 'cat-food', NULL, 'Groceries at supermarket', '2026-08-02', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-016', 'user-student-0001', 'expense', 25.0, 'cat-transport', NULL, 'Monthly bus pass', '2026-08-03', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-017', 'user-student-0001', 'expense', 12.99, 'cat-entertainment', NULL, 'Netflix subscription', '2026-08-05', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-018', 'user-student-0001', 'expense', 18.4, 'cat-food', NULL, 'Pizza with friends', '2026-08-07', 'Cash', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-019', 'user-student-0001', 'expense', 35.0, 'cat-bills', NULL, 'Phone data plan', '2026-08-09', 'Mobile money', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-020', 'user-student-0001', 'expense', 75.0, 'cat-education', NULL, 'Textbooks and printing', '2026-08-11', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-021', 'user-student-0001', 'expense', 22.75, 'cat-food', NULL, 'Cafeteria lunches', '2026-08-13', 'Cash', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-022', 'user-student-0001', 'expense', 40.0, 'cat-shopping', NULL, 'New t-shirt', '2026-08-16', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-023', 'user-student-0001', 'expense', 50.0, 'cat-savings', NULL, 'Transfer to savings', '2026-08-20', 'Cash', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-024', 'user-student-0001', 'expense', 9.5, 'cat-transport', NULL, 'Uber ride home', '2026-08-22', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-025', 'user-student-0001', 'expense', 15.0, 'cat-entertainment', NULL, 'Cinema tickets', '2026-08-25', 'Cash', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-026', 'user-student-0001', 'income', 500.0, NULL, 'Monthly allowance', NULL, '2026-09-01', 'Bank transfer', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-027', 'user-student-0001', 'income', 180.0, NULL, 'Part-time tutoring', NULL, '2026-09-15', 'Bank transfer', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-028', 'user-student-0001', 'expense', 42.5, 'cat-food', NULL, 'Groceries at supermarket', '2026-09-02', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-029', 'user-student-0001', 'expense', 25.0, 'cat-transport', NULL, 'Monthly bus pass', '2026-09-03', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-030', 'user-student-0001', 'expense', 12.99, 'cat-entertainment', NULL, 'Netflix subscription', '2026-09-05', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-031', 'user-student-0001', 'expense', 18.4, 'cat-food', NULL, 'Pizza with friends', '2026-09-07', 'Cash', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-032', 'user-student-0001', 'expense', 35.0, 'cat-bills', NULL, 'Phone data plan', '2026-09-09', 'Mobile money', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-033', 'user-student-0001', 'expense', 60.0, 'cat-education', NULL, 'Textbooks and printing', '2026-09-11', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-034', 'user-student-0001', 'expense', 22.75, 'cat-food', NULL, 'Cafeteria lunches', '2026-09-13', 'Cash', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-035', 'user-student-0001', 'expense', 45.0, 'cat-shopping', NULL, 'New t-shirt', '2026-09-16', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-036', 'user-student-0001', 'expense', 50.0, 'cat-savings', NULL, 'Transfer to savings', '2026-09-20', 'Cash', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-037', 'user-student-0001', 'expense', 9.5, 'cat-transport', NULL, 'Uber ride home', '2026-09-22', 'Card', NULL, '2026-09-24T14:43:53.874524');
INSERT INTO Transactions (TransactionId, UserId, Type, Amount, CategoryId, Source, Description, Date, PaymentMode, ReceiptImageUrl, CreatedAt) VALUES ('tx-demo-038', 'user-student-0001', 'expense', 15.0, 'cat-entertainment', NULL, 'Cinema tickets', '2026-09-24', 'Cash', NULL, '2026-09-24T14:43:53.874524');

-- Budgets (4)
INSERT INTO Budgets (BudgetId, UserId, Month, CategoryId, LimitAmount, AlertThreshold, CreatedAt) VALUES ('budget-demo-001', 'user-student-0001', '2026-09', NULL, 450.0, 80, '2026-09-24T14:43:53.874524');
INSERT INTO Budgets (BudgetId, UserId, Month, CategoryId, LimitAmount, AlertThreshold, CreatedAt) VALUES ('budget-demo-002', 'user-student-0001', '2026-09', 'cat-food', 100.0, 80, '2026-09-24T14:43:53.874524');
INSERT INTO Budgets (BudgetId, UserId, Month, CategoryId, LimitAmount, AlertThreshold, CreatedAt) VALUES ('budget-demo-003', 'user-student-0001', '2026-09', 'cat-entertainment', 30.0, 80, '2026-09-24T14:43:53.874524');
INSERT INTO Budgets (BudgetId, UserId, Month, CategoryId, LimitAmount, AlertThreshold, CreatedAt) VALUES ('budget-demo-004', 'user-student-0001', '2026-09', 'cat-shopping', 60.0, 80, '2026-09-24T14:43:53.874524');

-- SavingsGoals (3)
INSERT INTO SavingsGoals (GoalId, UserId, GoalName, TargetAmount, CurrentAmount, TargetDate, MonthlyContribution, Status, Milestones, CreatedAt, CompletedAt) VALUES ('goal-demo-001', 'user-student-0001', 'New laptop', 900.0, 320.0, '2027-07-01', 75.0, 'active', '25', '2026-09-24T14:43:53.874524', NULL);
INSERT INTO SavingsGoals (GoalId, UserId, GoalName, TargetAmount, CurrentAmount, TargetDate, MonthlyContribution, Status, Milestones, CreatedAt, CompletedAt) VALUES ('goal-demo-002', 'user-student-0001', 'Emergency fund', 500.0, 150.0, '2027-02-01', 50.0, 'active', '25', '2026-09-24T14:43:53.874524', NULL);
INSERT INTO SavingsGoals (GoalId, UserId, GoalName, TargetAmount, CurrentAmount, TargetDate, MonthlyContribution, Status, Milestones, CreatedAt, CompletedAt) VALUES ('goal-demo-003', 'user-student-0001', 'Concert ticket', 120.0, 120.0, '2026-08-01', 40.0, 'completed', '25,50,75,100', '2026-09-24T14:43:53.874524', '2026-09-24T14:43:53.874524');

-- LearningContent (9)
INSERT INTO LearningContent (ContentId, Title, Topic, Body, DifficultyLevel, ImageUrl, IsActive) VALUES ('learn-001', 'What is a budget?', 'Budgeting', 'A budget is a plan for your money. You list the money you expect to receive (income) and decide in advance how much will go to each kind of spending and to savings.

Example: You get 400 a month. You plan 150 for food, 60 for transport, 40 for phone and bills, 50 for fun, 50 for study materials and 50 for savings. That adds up to 400, so every unit has a job.

Tip: Review your budget at the end of each month. Move money from categories you did not use to the ones that ran short, and try again next month.', 'Beginner', 'education', 1);
INSERT INTO LearningContent (ContentId, Title, Topic, Body, DifficultyLevel, ImageUrl, IsActive) VALUES ('learn-002', 'The 50/30/20 rule', 'Budgeting', 'A simple starting point for splitting income:

• 50% for needs – food, rent, transport, bills.
• 30% for wants – entertainment, eating out, shopping.
• 20% for savings and paying back any debt.

Students often have fewer fixed bills, so you might save more than 20%. Treat the rule as a guide, not a law – adjust it to your own situation.', 'Beginner', 'bills', 1);
INSERT INTO LearningContent (ContentId, Title, Topic, Body, DifficultyLevel, ImageUrl, IsActive) VALUES ('learn-003', 'Pay yourself first', 'Saving', 'Move money into savings as soon as you receive it, instead of saving "whatever is left" at the end of the month – usually nothing is left!

Example: When your allowance arrives, put 10% straight into your savings goal in PennyPal. Then budget the other 90%.

Small amounts add up: saving 5 a day becomes about 150 a month and 1,800 a year.', 'Beginner', 'savings', 1);
INSERT INTO LearningContent (ContentId, Title, Topic, Body, DifficultyLevel, ImageUrl, IsActive) VALUES ('learn-004', 'Building an emergency fund', 'Saving', 'An emergency fund is money kept aside for surprises: a broken phone screen, a medical bill or an unexpected trip home.

Aim for one month of expenses first, then grow it to three months. Keep it separate from your spending money so you are not tempted to use it.

Create a savings goal called "Emergency fund" in PennyPal and add a small monthly contribution.', 'Intermediate', 'savings', 1);
INSERT INTO LearningContent (ContentId, Title, Topic, Body, DifficultyLevel, ImageUrl, IsActive) VALUES ('learn-005', 'Understanding your income', 'Income', 'Income is any money you receive: allowance, scholarships, internship stipends, part-time jobs or gifts.

Some income is regular (a monthly allowance) and some is irregular (freelance work, gifts). Build your budget on the regular income, and treat irregular income as a bonus – save part of it.

Record every income entry in PennyPal so your available balance is always accurate.', 'Beginner', 'gift', 1);
INSERT INTO LearningContent (ContentId, Title, Topic, Body, DifficultyLevel, ImageUrl, IsActive) VALUES ('learn-006', 'Needs vs. wants', 'Expenses', 'Necessary expenses (needs) are things you must pay for to live and study: food, transport to class, required books, rent and basic bills.

Optional expenses (wants) make life nicer but can be reduced: takeaway coffee, new clothes, streaming services, concerts.

Before buying, ask: "Do I need this, or do I want it?" If it is a want, wait 24 hours. If you still want it and it fits your budget, go ahead.', 'Beginner', 'shopping', 1);
INSERT INTO LearningContent (ContentId, Title, Topic, Body, DifficultyLevel, ImageUrl, IsActive) VALUES ('learn-007', 'Spotting small leaks', 'Expenses', 'Small, frequent purchases are the easiest way to overspend without noticing: snacks, delivery fees, in-app purchases and unused subscriptions.

Use the Transaction History filter in PennyPal to view one category for the month. If Food shows many small entries, try packing lunch twice a week and compare the next month.', 'Intermediate', 'food', 1);
INSERT INTO LearningContent (ContentId, Title, Topic, Body, DifficultyLevel, ImageUrl, IsActive) VALUES ('learn-008', 'Planning for study requirements', 'Requirements', 'Every term brings required costs: textbooks, lab fees, printing, software and exam registrations. They are easy to forget because they are not monthly.

Make a list at the start of the term, estimate the total and divide it by the months until you need the money. Add that amount to your Education budget each month.

Look for second-hand books, library copies and student discounts before paying full price.', 'Beginner', 'education', 1);
INSERT INTO LearningContent (ContentId, Title, Topic, Body, DifficultyLevel, ImageUrl, IsActive) VALUES ('learn-009', 'Setting SMART savings goals', 'Saving', 'Good goals are Specific, Measurable, Achievable, Relevant and Time-bound.

Weak goal: "Save money."
SMART goal: "Save 300 for a new laptop bag by 30 June by putting aside 50 a month."

PennyPal calculates how long your goal will take at your monthly contribution and warns you if you are behind schedule.', 'Intermediate', 'sport', 1);

-- Notifications (1)
INSERT INTO Notifications (NotificationId, UserId, Title, Message, Type, ReadStatus, CreatedAt) VALUES ('notif-demo-001', 'user-student-0001', 'Welcome to PennyPal!', 'Start by adding your income, then set a monthly budget to get alerts before you overspend.', 'system', 0, '2026-09-24T14:43:53.874524');

-- SupportQueries (1)
INSERT INTO SupportQueries (QueryId, UserId, Subject, Message, Status, AdminResponse, SubmittedOn) VALUES ('query-demo-001', 'user-student-0001', 'How do I change my currency?', 'I moved abroad for my exchange semester. Can I show amounts in EUR?', 'resolved', 'Yes! Open More > Profile & settings and choose EUR under Currency.', '2026-09-24T14:43:53.874524');

-- Feedback (1)
INSERT INTO Feedback (FeedbackId, UserId, Name, Email, Rating, Comments, SubmittedOn) VALUES ('feedback-demo-001', 'user-student-0001', 'Ada Student', 'student@pennypal.app', 5, 'The budget alerts helped me stop overspending on food.', '2026-09-24T14:43:53.874524');

-- AppSettings (3)
INSERT INTO AppSettings (SettingKey, SettingValue) VALUES ('default_alert_threshold', '80');
INSERT INTO AppSettings (SettingKey, SettingValue) VALUES ('chatbot_enabled', '1');
INSERT INTO AppSettings (SettingKey, SettingValue) VALUES ('support_email', 'support@pennypal.app');

COMMIT;
