// Writes database/pennypal_seed_data.sql: INSERT statements for the data the
// app seeds on first launch (admin account, categories, lessons, settings and
// the demo student's test records). Run from the project root with:
//
//   flutter test tool/export_seed_sql_test.dart
//
// It lives in tool/ (not test/) so normal test runs do not rewrite the file.
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../test/test_helpers.dart';

const tables = [
  'Users',
  'UserProfiles',
  'Categories',
  'Transactions',
  'Budgets',
  'SavingsGoals',
  'LearningContent',
  'Notifications',
  'SupportQueries',
  'Feedback',
  'AppSettings',
];

String sqlValue(Object? v) {
  if (v == null) return 'NULL';
  if (v is num) return '$v';
  return "'${v.toString().replaceAll("'", "''")}'";
}

void main() {
  test('export seed data', () async {
    final db = await openTestDatabase();
    final out = StringBuffer()
      ..writeln('-- =====================================================================')
      ..writeln('-- PennyPal - seed and test data')
      ..writeln('-- Generated by tool/export_seed_sql_test.dart on ${DateTime.now().toIso8601String().substring(0, 10)}.')
      ..writeln('-- Run after pennypal_schema.sql:  sqlite3 pennypal.db < pennypal_seed_data.sql')
      ..writeln('-- Demo transactions are dated relative to the generation date.')
      ..writeln('-- Logins: admin@pennypal.app / Admin@123, student@pennypal.app / Student@123')
      ..writeln('-- =====================================================================')
      ..writeln()
      ..writeln('BEGIN TRANSACTION;');
    for (final t in tables) {
      final rows = await db.db.query(t);
      if (rows.isEmpty) continue;
      out
        ..writeln()
        ..writeln('-- $t (${rows.length})');
      for (final r in rows) {
        out.writeln(
            'INSERT INTO $t (${r.keys.join(', ')}) VALUES (${r.values.map(sqlValue).join(', ')});');
      }
    }
    out
      ..writeln()
      ..writeln('COMMIT;');
    File('database/pennypal_seed_data.sql').writeAsStringSync(out.toString());
    await db.close();
  });
}
